export const es_EC = {
  BANK: 'Banco',
  SEACRH: 'Buscar...',
  SEARCH_VALUE_REQUIRED: 'El valor ',
  WRONG_SEARCH_VALUE: '',
  ID: 'ID',
  NAME: 'Nombre',
  DESCRIPTION: 'Descripción',
  LOGO: 'Logo',
  DELIVERY_DATE: 'Fecha liberación',
  REVISION_DATE: 'Fecha revisión',
  SEND: 'Envíar',
  RESET: 'Reiniciar',
  EDIT: 'Editar',
  DELETE: 'Eliminar',
  CONFIRM: 'Confirmar',
  CANCEL: 'Cancelar',
  CONFIRM_DELETE: '¿Estás seguro de eliminar el producto ',
  ADD: 'Agregar',
  REGISTER_FORM: 'Formulario de registro',
  FIELD_REQUIRED: 'Este campo es requerido!',
  INVALID_ID: 'Id no válido.',
  INVALID_NAME: 'Nombre no válido.',
  INVALID_DESCRIPTION: 'Descripcion no válido.',
  INVALID_LOGO: 'Logo no válido.',
  INVALID_DELIVERY_DATE: 'Fecha de liberación no válido.',
  INVALID_REVISION_dATE: 'Fecha de revisión no válido.',
  AN_ERROR_OCCURRED: 'Ha ocurrido un error inesperado, intente más tarde.',
  NOT_DATA: 'No hay datos por mostrar.',
  DUPLICATE_PRODUCT: 'Este producto con el id indicado ya ha sido registrado.',
  PRODUCT_NOT_EXISIT: 'El producto seleccionado no existe.',
};
